name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: liquidcan_rust
      run: cargo build --verbose
    - name: Run tests
      working-directory: liquidcan_rust
      run: cargo test --verbose
    - name: Run macro tests
      working-directory: liquidcan_rust/liquidcan_rust_macros
      run: cargo test --verbose
    - name: Check formatting
      working-directory: liquidcan_rust
      run: cargo fmt --all -- --check
    - name: Run clippy
      working-directory: liquidcan_rust
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run clippy on macros
      working-directory: liquidcan_rust/liquidcan_rust_macros
      run: cargo clippy --all-targets --all-features -- -D warnings
